export const SHOT_CONFIG = {
  preReleaseMs: 1200,
  postReleaseMs: 800,
  // Keeps the manual pre-shot window plus enough bounded history for a user to
  // confirm an experimental candidate before its original pre-window expires.
  bufferDurationMs: 2800,
  minimumPreReleaseMs: 900,
  minimumPreReleaseSamples: 8,
  minimumMetricSamples: 2,
  minLandmarkQuality: 0.55,
  releaseCooldownMs: 1000,
  maxSampleGapMs: 300,
  releaseWindowToleranceMs: 180,
  anchorStartMs: -600,
  anchorEndMs: -100,
  releaseStartMs: -100,
  releaseEndMs: 100,
  followThroughStartMs: 100,
  followThroughEndMs: 700,
  comparisonPreStartMs: -180,
  comparisonPreEndMs: -40,
  comparisonPostStartMs: 40,
  comparisonPostEndMs: 180,
  candidateThreshold: 0.68,
  candidateDebounceMs: 300,
  candidateCooldownMs: 1600,
  candidateConfirmWindowMs: 1400,
  candidateStartupMs: 1200,
  candidateRecoveryMs: 700,
  candidateDrawWristVelocity: 0.7,
  candidateDrawElbowVelocity: 0.35,
  candidateBowWristVelocity: 0.3,
  candidateGlobalMotionRejectVelocity: 0.35,
  candidateHeadMotionRejectVelocity: 0.3,
  candidateTorsoChangeRejectDeg: 3,
  dataQualityGoodRatio: 0.85,
  dataQualityGoodConfidence: 0.7,
  dataQualityLimitedRatio: 0.6,
  sessionMinimumShots: 2,
} as const;
