import type { BiomechanicsSnapshot } from '../types/biomechanics';
import type { AnalysisShot } from '../analytics/analysisDataset';
import { mean, median, pearsonCorrelation, standardDeviation } from '../analytics/statistics';
import { scoreTargetCoordinate } from '../target/targetGeometry';

export const SIMULATION_CONFIG = { minimumTargetShots: 5, minimumRelationshipShots: 8, minimumRelationshipStrength: 0.3, adjustmentShrinkage: 0.35, maximumCenterShift: 0.2, minimumVarianceMultiplier: 0.75, maximumVarianceMultiplier: 1.5 } as const;
export interface SimulationInput { historicalShots: AnalysisShot[]; currentBiomechanics?: BiomechanicsSnapshot; simulationCount: number; seed?: number; random?: () => number }
export interface SimulatedImpact { x: number; y: number }
export interface SimulationOutput { impacts: SimulatedImpact[]; centerX: number; centerY: number; horizontalSpread: number; verticalSpread: number; radialSpread: number; probabilities: { x: number; ten: number; nine: number; eight: number; sevenOrLower: number; miss: number; ninePlus: number; tenOrX: number }; historicalShotCount: number; exactLocationCount: number; adjustments: string[] }
export function seededRandom(seed: number): () => number { let state = seed >>> 0; return () => { state += 0x6D2B79F5; let value = state; value = Math.imul(value ^ value >>> 15, value | 1); value ^= value + Math.imul(value ^ value >>> 7, value | 61); return ((value ^ value >>> 14) >>> 0) / 4294967296; }; }
function normal(random: () => number): number { const u = Math.max(Number.EPSILON, random()); return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * random()); }
const clamp = (value: number, limit: number) => Math.max(-limit, Math.min(limit, value));

export function simulateShotDistribution(input: SimulationInput): SimulationOutput {
  const points = input.historicalShots.filter((row): row is AnalysisShot & { targetX: number; targetY: number } => row.targetX !== null && row.targetY !== null);
  if (points.length < SIMULATION_CONFIG.minimumTargetShots) throw new Error('Add more exact target positions to enable simulation.');
  if (![100, 1000, 10000].includes(input.simulationCount)) throw new Error('Simulation count must be 100, 1,000, or 10,000.');
  const xs = points.map((point) => point.targetX); const ys = points.map((point) => point.targetY); let centerX = mean(xs)!; let centerY = mean(ys)!;
  const sdX = standardDeviation(xs, false) ?? 0; const sdY = standardDeviation(ys, false) ?? 0; const covariance = mean(points.map((point) => (point.targetX - centerX) * (point.targetY - centerY))) ?? 0; const correlation = sdX && sdY ? Math.max(-0.98, Math.min(0.98, covariance / (sdX * sdY))) : 0;
  let varianceMultiplier = 1; const adjustments: string[] = []; const current = input.currentBiomechanics;
  const adjust = (field: 'shoulderDeltaDeg' | 'torsoDeltaDeg', target: 'x' | 'y', currentValue?: number | null) => { if (typeof currentValue !== 'number' || !Number.isFinite(currentValue)) return; const paired = points.filter((point) => point[field] !== null); if (paired.length < SIMULATION_CONFIG.minimumRelationshipShots) return; const metric = paired.map((point) => point[field]!); const targetValues = paired.map((point) => target === 'x' ? point.targetX : point.targetY); const relationship = pearsonCorrelation(metric, targetValues); const metricSd = standardDeviation(metric, false) ?? 0; const targetSd = standardDeviation(targetValues, false) ?? 0; if (relationship === null || Math.abs(relationship) < SIMULATION_CONFIG.minimumRelationshipStrength || metricSd === 0) return; const shift = clamp((currentValue - median(metric)!) * relationship * targetSd / metricSd * SIMULATION_CONFIG.adjustmentShrinkage, SIMULATION_CONFIG.maximumCenterShift); if (target === 'x') centerX += shift; else centerY += shift; adjustments.push(`${field} vs target${target.toUpperCase()}`); };
  adjust('shoulderDeltaDeg', 'x', current?.reference?.shoulderDeltaDeg); adjust('torsoDeltaDeg', 'y', current?.reference?.torsoDeltaDeg);
  const bowPairs = points.filter((point) => point.bowHandDisplacement !== null && point.radialError !== null); const currentBow = current?.bowHandMotion.value;
  if (typeof currentBow === 'number' && bowPairs.length >= SIMULATION_CONFIG.minimumRelationshipShots) { const bows = bowPairs.map((point) => point.bowHandDisplacement!); const relationship = pearsonCorrelation(bows, bowPairs.map((point) => point.radialError!)); const bowSd = standardDeviation(bows, false) ?? 0; if (relationship !== null && Math.abs(relationship) >= SIMULATION_CONFIG.minimumRelationshipStrength && bowSd > 0) { varianceMultiplier = Math.max(SIMULATION_CONFIG.minimumVarianceMultiplier, Math.min(SIMULATION_CONFIG.maximumVarianceMultiplier, 1 + ((currentBow - median(bows)!) / bowSd) * relationship * 0.15)); adjustments.push('bowHandDisplacement vs radial spread'); } }
  const random = input.random ?? seededRandom(input.seed ?? Date.now()); const impacts: SimulatedImpact[] = new Array(input.simulationCount); const safeSdX = sdX * varianceMultiplier; const safeSdY = sdY * varianceMultiplier; const residual = Math.sqrt(1 - correlation ** 2); const buckets = { x: 0, ten: 0, nine: 0, eight: 0, sevenOrLower: 0, miss: 0 };
  for (let index = 0; index < impacts.length; index += 1) { const z1 = normal(random); const point = { x: centerX + safeSdX * z1, y: centerY + safeSdY * (correlation * z1 + residual * normal(random)) }; impacts[index] = point; const score = scoreTargetCoordinate(point.x, point.y); if (score.isX) buckets.x++; else if (score.score === 10) buckets.ten++; else if (score.score === 9) buckets.nine++; else if (score.score === 8) buckets.eight++; else if (score.score === 0) buckets.miss++; else buckets.sevenOrLower++; }
  const percent = (count: number) => count / impacts.length * 100;
  return { impacts, centerX, centerY, horizontalSpread: safeSdX, verticalSpread: safeSdY, radialSpread: Math.hypot(safeSdX, safeSdY), historicalShotCount: input.historicalShots.length, exactLocationCount: points.length, adjustments, probabilities: { x: percent(buckets.x), ten: percent(buckets.ten), nine: percent(buckets.nine), eight: percent(buckets.eight), sevenOrLower: percent(buckets.sevenOrLower), miss: percent(buckets.miss), ninePlus: percent(buckets.x + buckets.ten + buckets.nine), tenOrX: percent(buckets.x + buckets.ten) } };
}
