import { useState, type PointerEvent } from 'react';
import { ActionButton } from '../components/ActionButton';
import { PageHeader } from '../components/PageHeader';
import { createTargetResult, screenPointToTargetCoordinates, scoreTargetCoordinate, type TargetCoordinate } from '../target/targetGeometry';
import type { ReportedShotResult } from '../types/gestureScore';
import type { ShotAnalysis } from '../types/shotAnalysis';

export function ManualShotEntryPage({ shot, onSave, onCancel }: { shot?: ShotAnalysis; onSave?: (result: ReportedShotResult) => void; onCancel?: () => void }) {
  const old = shot?.actualResult?.targetResult;
  const [target, setTarget] = useState<TargetCoordinate | undefined>(old?.targetX != null && old.targetY != null ? { x: old.targetX, y: old.targetY } : undefined);
  const [previous, setPrevious] = useState<TargetCoordinate>();
  const [manualScore, setManualScore] = useState(shot?.actualResult ? (shot.actualResult.isX ? 'X' : shot.actualResult.score === 0 ? 'M' : String(shot.actualResult.score)) : '10');
  const [notes, setNotes] = useState(shot?.actualResult?.notes ?? '');
  const scored = target ? scoreTargetCoordinate(target.x, target.y) : undefined;
  const update = (event: PointerEvent<HTMLButtonElement>) => { event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); const bounds = event.currentTarget.getBoundingClientRect(); setPrevious(target); setTarget(screenPointToTargetCoordinates(event.clientX, event.clientY, bounds)); };
  const gesture = shot?.actualResult?.source === 'gesture';
  const mismatch = Boolean(gesture && scored && (shot!.actualResult!.score !== scored.score || shot!.actualResult!.isX !== scored.isX));
  const save = (useTarget = !gesture) => { if (!shot) return; const targetResult = target ? createTargetResult(target.x, target.y) : undefined; const entered = manualScore === 'X' ? 10 : manualScore === 'M' ? 0 : Number(manualScore); const score = useTarget && targetResult ? targetResult.score! : gesture ? shot.actualResult!.score : entered; const isX = useTarget && targetResult ? targetResult.isX : gesture ? shot.actualResult!.isX : manualScore === 'X'; onSave?.({ score, isX, source: gesture && !useTarget ? 'gesture' : targetResult && useTarget ? 'manual-target' : 'manual-score', capturedAt: shot.actualResult?.capturedAt ?? Date.now(), gestureConfidence: shot.actualResult?.gestureConfidence, gestureId: shot.actualResult?.gestureId, targetX: target?.x ?? null, targetY: target?.y ?? null, targetResult, alternateScore: mismatch ? { score: useTarget ? shot.actualResult!.score : targetResult!.score!, isX: useTarget ? shot.actualResult!.isX : targetResult!.isX, source: useTarget ? 'gesture' : 'manual-target' } : undefined, notes }); };
  return <div className="manual-target-page"><PageHeader title="Manual Shot Entry" subtitle={shot ? `Shot ${shot.id} · tap or drag to record the actual impact` : 'Capture a shot first'} compact />
    <section className="manual-target-card"><span className="eyebrow">Exact target position</span><button type="button" aria-label="Target face" onPointerDown={update} onPointerMove={(event) => { if (event.buttons === 1) update(event); }} className="target-face">{target ? <span className="target-marker" style={{ left: `${(target.x + 1) * 50}%`, top: `${(target.y + 1) * 50}%` }} /> : null}</button><div className="target-reading"><strong>{scored?.label ?? '--'}</strong><span>{target ? `x ${target.x.toFixed(2)} · y ${target.y.toFixed(2)} · r ${Math.hypot(target.x, target.y).toFixed(2)}` : 'Tap target to place arrow'}</span></div><div className="target-actions"><button disabled={!previous} onClick={() => { setTarget(previous); setPrevious(undefined); }}>Undo</button><button disabled={!target} onClick={() => { setPrevious(target); setTarget(undefined); }}>Clear</button><button onClick={onCancel}>Cancel</button></div></section>
    {!gesture ? <section className="manual-score-card"><h3>Reported score</h3><div className="score-keypad">{['X','10','9','8','7','6','5','4','3','2','1','M'].map((value) => <button key={value} className={manualScore === value ? 'is-selected' : ''} onClick={() => setManualScore(value)}>{value}</button>)}</div></section> : <section className="result-source-card"><span>Gesture Result</span><strong>{shot!.actualResult!.isX ? 'X' : shot!.actualResult!.score}</strong><small>Exact location does not silently replace this athlete-reported score.</small></section>}
    {mismatch ? <section className="result-mismatch"><strong>Result mismatch</strong><span>Gesture Result: {shot!.actualResult!.score} · Target Result: {scored!.label}</span><div><button onClick={() => save(false)}>Use Gesture Score</button><button onClick={() => save(true)}>Use Target Score</button></div></section> : null}
    <label className="target-notes">Notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>{!mismatch ? <ActionButton className="w-full justify-center" disabled={!shot || (!target && !shot?.actualResult)} onClick={() => save()}>Confirm Shot Result</ActionButton> : null}
  </div>;
}
