import { ShotMetricCard } from '../components/shot/ShotMetricCard';
import { ShotMetricChart } from '../components/shot/ShotMetricChart';
import { ShotTimeline } from '../components/shot/ShotTimeline';
import { PageHeader } from '../components/PageHeader';
import { StatusBadge } from '../components/StatusBadge';
import type { ShotAnalysis } from '../types/shotAnalysis';

export function ReplayAnalysisPage({ shot, shotNumber, onManualEntry, onUndoScore }: { shot?: ShotAnalysis; shotNumber: number; onManualEntry?: () => void; onUndoScore?: () => void }) {
  if (!shot) return <div className="page-container"><PageHeader title="Biomechanics Replay" subtitle="Capture a shot in Live Analysis to create a replay." /></div>;
  const release = shot.releaseMetrics;
  return <div className="replay-page"><PageHeader title={`Shot #${shotNumber}`} subtitle={`Release source: ${shot.releaseSource === 'manual' ? 'Manual' : 'Automatic candidate confirmed'}`} actions={<StatusBadge label={`Data quality: ${shot.dataQuality.label}`} tone={shot.dataQuality.label === 'Good' ? 'success' : 'warning'} compact />} />
    <section className="shot-result-header"><div><span>Captured samples</span><strong>{shot.frames.length}</strong></div><div><span>Usable frames</span><strong>{Math.round(shot.dataQuality.usableFrameRatio * 100)}%</strong></div><div><span>Average pose confidence</span><strong>{Math.round(shot.dataQuality.averagePoseConfidence * 100)}%</strong></div><div><span>Tracking loss</span><strong>{Math.round(shot.dataQuality.trackingLossMs)} ms</strong><small>{shot.dataQuality.releaseWindowComplete ? 'Release window complete' : 'Release window incomplete'}</small></div><div><span>Athlete reported</span><strong>{shot.actualResult ? shot.actualResult.isX ? 'X' : shot.actualResult.score : '--'}</strong><small>{shot.actualResult ? `${shot.actualResult.source} entry` : 'Not entered'}</small></div></section>
    <ShotTimeline shot={shot} />
    <section className="shot-chart-grid"><ShotMetricChart shot={shot} field="shoulderLineAngleDeg" label="Shoulder Line Angle" unit="°" /><ShotMetricChart shot={shot} field="bowArmElbowAngleDeg" label="Bow Arm Angle" unit="°" /><ShotMetricChart shot={shot} field="torsoLeanDeg" label="Torso Lean" unit="°" /><ShotMetricChart shot={shot} field="headMotion" label="Head Motion" unit="% SW" /><ShotMetricChart shot={shot} field="bowHandMotion" label="Bow-Hand Motion" unit="% SW" /></section>
    <section><div className="analytics-panel__header"><div><span className="eyebrow">Release comparison</span><h2>Before / after / delta</h2></div></div><div className="release-comparison-grid">{[['Shoulder line', release.shoulder], ['Bow arm', release.bowArm], ['Torso lean', release.torso]].map(([label, comparison]) => { const item = comparison as typeof release.shoulder; return <article key={label as string}><strong>{label as string}</strong><span>Before {item.before.available ? `${item.before.value!.toFixed(1)}°` : '--'}</span><span>After {item.after.available ? `${item.after.value!.toFixed(1)}°` : '--'}</span><span>Delta {item.delta.available ? `${item.delta.value! >= 0 ? '+' : ''}${item.delta.value!.toFixed(1)}°` : '--'}</span></article>; })}</div></section>
    <section className="release-comparison-grid"><article><strong>Head displacement</strong><span>Across release</span><span>{release.headDisplacement.available ? `${release.headDisplacement.value!.toFixed(1)} % SW` : release.headDisplacement.reason ?? '--'}</span></article><article><strong>Bow-hand displacement</strong><span>Across release</span><span>{release.bowHandDisplacement.available ? `${release.bowHandDisplacement.value!.toFixed(1)} % SW` : release.bowHandDisplacement.reason ?? '--'}</span></article></section>
    <section className="shot-summary-grid"><ShotMetricCard title="Hold shoulder variation" metric={shot.summary.holdShoulderVariationDeg} /><ShotMetricCard title="Hold bow-arm variation" metric={shot.summary.holdBowArmVariationDeg} /><ShotMetricCard title="Hold torso variation" metric={shot.summary.holdTorsoVariationDeg} /><ShotMetricCard title="Head displacement" metric={release.headDisplacement} /><ShotMetricCard title="Bow-hand displacement" metric={release.bowHandDisplacement} /><ShotMetricCard title="Follow-through shoulder variation" metric={release.followThroughShoulderVariation} /><ShotMetricCard title="Follow-through torso variation" metric={release.followThroughTorsoVariation} /><ShotMetricCard title="Follow-through head motion" metric={release.followThroughHeadMotion} /><ShotMetricCard title="Follow-through bow-hand motion" metric={release.followThroughBowHandMotion} /></section>
    <div className="replay-actions"><button type="button" onClick={onManualEntry}>Add Actual Result</button>{shot.actualResult ? <button type="button" onClick={onUndoScore}>Undo Score</button> : null}</div>
  </div>;
}
